#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec "htmlproofer ./_site --disable-external --allow-hash-href true --empty-alt-ignore true --alt-ignore '/.*/' --directory-index-file index.html"